apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: downstream-logging
  namespace: cattle-logging-system
spec:
  filters:
  - dedot:
      de_dot_nested: true
      de_dot_separator: _
  globalOutputRefs:
  - logging-output
  match:
  - exclude:
      namespaces:
      - kube-system
      - cattle-logging-system
  - select: {}