apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: logging-output
  namespace: cattle-logging-system
spec:
  elasticsearch:
    buffer:
      flush_interval: 5s
      flush_thread_count: 8
      timekey: 1m
      timekey_use_utc: true
      timekey_wait: 30s
    host: <elsaticapi>
    include_timestamp: true
    index_name: sample-%Y.%m.%d
    log_es_400_reason: true
    password:
      valueFrom:
        secretKeyRef:
          key: password
          name: elastic-connection
    port: 9200
    scheme: http
    ssl_verify: false
    ssl_version: TLSv1_2
    user: elasticsearch